- type: job
  id: BrightEye
  name: job-name-bright
  description: job-description-bright
  playTimeTracker: JobBrightEye
  startingGear: CBURNGear
  icon: "JobIconNanotrasen"
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 172800 # 48 hrs
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]